# VictoriaMetrics Cluster DEV overrides — minimal resources
vmselect:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  ingress:
    hosts:
      - name: metrics.alloysoftware.us
        path: /
    tls:
      - secretName: alloysoftware-us-tls
        hosts:
          - metrics.alloysoftware.us

vminsert:
  replicaCount: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - name: push.alloysoftware.us
        path: /
    tls:
      - secretName: alloysoftware-us-tls
        hosts:
          - push.alloysoftware.us
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

vmstorage:
  replicaCount: 1
  retentionPeriod: "7d"
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
