apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/grafana/helm-charts.git
      path: charts/grafana
      targetRevision: grafana-10.5.15
      helm:
        valueFiles:
          - $values/values/grafana/base/core.yaml
          - $values/values/grafana/base/datasources/victoria.yaml
          - $values/values/grafana/base/dashboards/sidecar.yaml
          - $values/values/grafana/base/alerting/contact-points.yaml
          - $values/values/grafana/base/alerting/policies.yaml
          - $values/values/grafana/base/alerting/rules/windows-exporter.yaml
    - repoURL: git@github.com:muzzai/testing_argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
