apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-certificates
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:muzzai/testing_argocd.git
    targetRevision: main
    path: manifests/monitoring-certificates/base
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
