apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/VictoriaMetrics/helm-charts.git
      path: charts/victoria-metrics-cluster
      targetRevision: victoria-metrics-cluster-0.35.0
      helm:
        valueFiles:
          - $values/values/victoria-metrics-cluster/base.yaml
    - repoURL: git@gitlab.alloysoftware.com:maintainers/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
